# Generated by Django 5.0.2 on 2024-03-26 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_rename_price_booking_total_price'),
        ('hotel', '0009_alter_bed_room_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookingroom',
            unique_together={('booking', 'room')},
        ),
    ]
