# Generated by Django 5.0.2 on 2024-03-18 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenityhotel',
            name='amenity',
        ),
        migrations.AddField(
            model_name='amenityhotel',
            name='amenity1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='amenityhotel',
            name='amenity2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='amenityhotel',
            name='amenity3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='amenityhotel',
            name='amenity4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='amenityhotel',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotel', to='hotel.hotel'),
        ),
    ]
