# Generated by Django 5.0.2 on 2024-03-20 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_remove_amenityhotel_amenity_amenityhotel_amenity1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenityhotel',
            name='amenity1',
        ),
        migrations.RemoveField(
            model_name='amenityhotel',
            name='amenity2',
        ),
        migrations.RemoveField(
            model_name='amenityhotel',
            name='amenity3',
        ),
        migrations.RemoveField(
            model_name='amenityhotel',
            name='amenity4',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='nbr_etoiles',
        ),
        migrations.AddField(
            model_name='amenityhotel',
            name='nbr_etoiles',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='telephone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
