# Generated by Django 5.0.2 on 2024-03-22 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_remove_roomtype_price_room_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BedType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='amenityhotel',
            name='nbr_etoiles',
        ),
        migrations.RemoveField(
            model_name='amenityroom',
            name='name',
        ),
        migrations.RemoveField(
            model_name='bed',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='room',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='room',
            name='nbr_bed',
        ),
        migrations.AddField(
            model_name='amenityroom',
            name='room',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hotel.room'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='hotel',
            name='nb_star',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='nb_bed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='amenityhotel',
            name='hotel',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel'),
        ),
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hotel.roomtype'),
        ),
        migrations.AddField(
            model_name='amenityhotel',
            name='amenity',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hotel.amenity'),
        ),
        migrations.AddField(
            model_name='amenityroom',
            name='amenity',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hotel.amenity'),
        ),
        migrations.CreateModel(
            name='Bed_room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hotel.bed')),
                ('room', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hotel.roomtype')),
            ],
        ),
        migrations.AddField(
            model_name='bed',
            name='bed_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hotel.bedtype'),
        ),
        migrations.DeleteModel(
            name='Bed_type',
        ),
    ]
