# Generated by Django 5.0.2 on 2024-03-22 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_amenity_bedtype_remove_amenityhotel_nbr_etoiles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenityhotel',
            name='amenity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.amenity'),
        ),
        migrations.AlterField(
            model_name='amenityhotel',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel'),
        ),
        migrations.AlterField(
            model_name='amenityroom',
            name='amenity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.amenity'),
        ),
        migrations.AlterField(
            model_name='amenityroom',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.room'),
        ),
        migrations.AlterField(
            model_name='bed',
            name='bed_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.bedtype'),
        ),
        migrations.AlterField(
            model_name='bed_room',
            name='bed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.bed'),
        ),
        migrations.AlterField(
            model_name='bed_room',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.roomtype'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.roomtype'),
        ),
    ]
